### PR TITLE
Make links easier to override

### PR DESCRIPTION
**Pull request by seanyesmunt**
I will probably end up making a few more of these as I run into them. The current setup makes it really difficult to override styling due to the high specificity of the default state.

This moves the `color` to the top level, then adds individual blocks for `:hover`, and `:disabled`

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@NetOperatorWibby The splash screen in the app. We turn all links white because of the green background. This makes it so we just need to add a separate class `load-screen__button` and the color will work.

Instead of having to do something like:
```
.button--link.load-screen__button:not(:disabled):not(:hover) { color: $lbry-white }
```

**Comment by NetOperatorWibby** [comment]
I don't think that's a reason to change the component logic. Loading screens are special cases, it makes sense to have to do specific things that only apply to them, within them.

**Comment by seanyesmunt** [comment]
I'm not changing the logic of this though. I'm just removing un-needed specificity.

**Comment by NetOperatorWibby** [comment]
The specificity applies to buttons that are not disabled. Disabled buttons shouldn't have styling applied to them. Component styles should not be overridden.

Why not just add an extra class for button links that should be white?

**Comment by seanyesmunt** [comment]
I removed the `:disabled` style. I realize that is not needed with `pointer-events: none` on disabled buttons.

I don't see why these can't be overridden though. I want the same style rules for it, but only want to change the color. If I need to use an entirely different class instead of combining them I will end up with duplicated code.

This change makes it so I can do this:
```
.load-screen__button {
  color: $lbry-white;

  &:hover {
    color: $lbry-blue-1;
  }
}
```

instead of

```
.load-screen__button:not(:disabled) {
  &:not(:hover) {
    color: $lbry-white;
  }

  &:hover {
    color: $lbry-blue-1;
  }
}
```

**Comment by NetOperatorWibby** [comment]
I suppose I can just prevent the rules for `[disabled]` and `.button--disabled` from being overridden.

The `test:sass` script needs to be run on this PR, then it'll be good for merge and I can deploy to npm.

**Comment by seanyesmunt** [comment]
@NetOperatorWibby Ran `test:sass`. Should be good I think.

**Pull request merged**
